"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = "$os  $username [in](dimmed white) $directory$git_branch$cmd_duration $character"

[username]
show_always = true
style_user = "bold #cdd6f4"
style_root = "bold #f38ba8"
format = "[$user]($style)"

[os]
disabled = false
style = "bold #89b4fa"

[os.symbols]
Arch = ""
Fedora = ""
Ubuntu = ""
Debian = ""
Alpine = ""
Linux = ""
Macos = ""
Windows = ""

[directory]
style = "bold #89b4fa"
home_symbol = "~"
read_only = "  "
truncation_length = 2
truncation_symbol = "../"
format = "[$path]($style)"

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "

[git_branch]
symbol = " "
style = "bold #cba6f7"
format = " [$symbol$branch]($style)"

[character]
success_symbol = "[»](bold #94e2d5)"
error_symbol = "[»](bold #f38ba8)"
vicmd_symbol = "[«](bold #f9e2af)"

[cmd_duration]
min_time = 100
style = "fg:#9399b2"
format = " [$duration]($style)"
