"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = "$os  $username [in](dimmed white) $directory$git_branch$cmd_duration $character"

[username]
show_always = true
style_user = "bold #ebdbb2"
style_root = "bold #fb4934"
format = "[$user]($style)"

[os]
disabled = false
style = "bold #83a598"

[os.symbols]
Arch = ""
Fedora = ""
Ubuntu = ""
Debian = ""
Alpine = ""
Linux = ""
Macos = ""
Windows = ""

[directory]
style = "bold #83a598"
home_symbol = "~"
read_only = "  "
truncation_length = 2
truncation_symbol = "../"
format = "[$path]($style)"

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "

[git_branch]
symbol = " "
style = "bold #d3869b"
format = " [$symbol$branch]($style)"

[character]
success_symbol = "[»](bold #8ec07c)"
error_symbol = "[»](bold #fb4934)"
vicmd_symbol = "[«](bold #fabd2f)"

[cmd_duration]
min_time = 100
style = "fg:#928374"
format = " [$duration]($style)"
