# vim:ft=kitty

## name:     Everforest Dark Hard
## author:   saghen, sainnhe
## license:  MIT
## upstream: https://github.com/sainnhe/everforest
## blurb:    A soothing, warm green-based color scheme for Kitty.



# The basic colors
foreground              #d3c6aa
background              #272e33
selection_foreground    #272e33
selection_background    #4c3743

# Cursor colors
cursor                  #d3c6aa
cursor_text_color       #272e33

# Scrollbar colors
scrollbar_handle_color  #7a8478
scrollbar_track_color   #374145

# URL color when hovering with mouse
url_color               #7fbbb3

# Kitty window border colors
active_border_color     #a7c080
inactive_border_color   #4f585e
bell_border_color       #dbbc7f

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #272e33
active_tab_background   #7fbbb3
inactive_tab_foreground #d3c6aa
inactive_tab_background #374145
tab_bar_background      #1e2326

# Colors for marks (marked text in the terminal)
mark1_foreground #272e33
mark1_background #a7c080
mark2_foreground #272e33
mark2_background #d699b6
mark3_foreground #272e33
mark3_background #83c092

# The 16 terminal colors

# black
color0  #414b50
color8  #7a8478

# red
color1  #e67e80
color9  #f85552

# green
color2  #a7c080
color10 #a7c080

# yellow
color3  #dbbc7f
color11 #dbbc7f

# blue
color4  #7fbbb3
color12 #7fbbb3

# magenta
color5  #d699b6
color13 #d699b6

# cyan
color6  #83c092
color14 #83c092

# white
color7  #d3c6aa
color15 #edeada