# vim:ft=kitty

foreground              #abb2bf
background              #282c34

selection_foreground    #282c34
selection_background    #3e4452

cursor                  #528bff
cursor_text_color       #282c34

url_color               #61afef

active_border_color     #61afef
inactive_border_color   #3e4452
bell_border_color       #e86671

active_tab_foreground   #282c34
active_tab_background   #61afef
inactive_tab_foreground #abb2bf
inactive_tab_background #3e4452

# Black
color0                  #282c34
color8                  #5c6370

# Red
color1                  #e86671
color9                  #e86671

# Green
color2                  #98c379
color10                 #98c379

# Yellow
color3                  #e5c07b
color11                 #e5c07b

# Blue
color4                  #61afef
color12                 #61afef

# Magenta
color5                  #c678dd
color13                 #c678dd

# Cyan
color6                  #56b6c2
color14                 #56b6c2

# White
color7                  #abb2bf
color15                 #ffffff